Exploring and Cleaning Data

In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()
TMDB_API_KEY = os.getenv('TMDB_API_KEY')

# Common Paths
data_path = Path('../data')
movie_lens = data_path / 'ml-100k'

# Load movie slugs(names) and ratings into single DataFrame
ratings = pd.read_csv(data_path / 'ratings.csv')
ratings.drop(columns=['Letterboxd URI', 'Date'], inplace=True)
ratings.head()

               Name  Year  Rating
0  Wicked: For Good  2025     2.0
1         Novocaine  2025     2.5
2          Zootopia  2016     4.0
3        Zootopia 2  2025     4.0
4         Road Trip  2000     3.5

In [2]:
tmdb_df = pd.read_csv(data_path / 'tmdb_metadata.csv')
tmdb_df.head()

   letterboxd_title  tmdb_id    original_title  release_year  rating
0  Wicked: For Good   967941  Wicked: For Good          2025     2.0
1         Novocaine  1195506         Novocaine          2025     2.5
2          Zootopia   269149          Zootopia          2016     4.0
3        Zootopia 2  1084242        Zootopia 2          2025     4.0
4         Road Trip     9285         Road Trip          2000     3.5

In [3]:
links = pd.read_csv(data_path / 'ml-32m' / 'links.csv')

matched = tmdb_df.merge(links, left_on='tmdb_id', right_on='tmdbId', how='inner').drop(columns=['tmdbId', 'imdbId'])

print(f"Your ratings:      {len(tmdb_df)}")
print(f"Matched in ml-32m: {len(matched)}")
print(f"Not found:         {len(tmdb_df) - len(matched)}")

display(matched)

Your ratings:      68
Matched in ml-32m: 32
Not found:         36

,letterboxd_title,tmdb_id,original_title,release_year,rating,movieId
0,Zootopia,269149,Zootopia,2016,4.0,152081
1,Road Trip,9285,Road Trip,2000,3.5,3617
2,The Terminal,594,The Terminal,2004,3.0,8529
3,Sonic the Hedgehog,454626,Sonic the Hedgehog,2020,2.5,210577
4,Sonic the Hedgehog 2,675353,Sonic the Hedgehog 2,2022,3.0,271799
5,Titanic,597,Titanic,1997,3.5,1721
6,Chef,212778,Chef,2014,3.5,111443
7,Coherence,220289,Coherence,2014,4.0,113741
8,Avatar,19995,Avatar,2009,3.5,72998
9,A Rainy Day in New York,475303,A Rainy Day in New York,2019,2.5,198157
10,The Princess Bride,2493,The Princess Bride,1987,3.5,1197
11,10 Things I Hate About You,4951,10 Things I Hate About You,1999,4.5,2572
12,The Nice Guys,290250,The Nice Guys,2016,4.0,158238
13,How to Lose a Guy in 10 Days,9919,How to Lose a Guy in 10 Days,2003,4.0,6155
14,Raiders of the Lost Ark,85,Raiders of the Lost Ark,1981,3.0,1198
15,Love Actually,508,Love Actually,2003,2.0,6942
16,The Notebook,11036,The Notebook,2004,4.0,8533
17,The Super Mario Bros. Movie,502356,The Super Mario Bros. Movie,2023,3.5,286131
18,The Prestige,1124,The Prestige,2006,4.5,48780
19,Shang-Chi and the Legend of the Ten Rings,566525,Shang-Chi and the Legend of the Ten Rings,2021,4.0,255335
20,Boogie Nights,4995,Boogie Nights,1997,3.0,1673
21,Gladiator,98,Gladiator,2000,4.5,3578
22,How to Train Your Dragon,10191,How to Train Your Dragon,2010,5.0,76093
23,Spider-Man: Far From Home,429617,Spider-Man: Far From Home,2019,4.0,201773
24,How to Train Your Dragon 2,82702,How to Train Your Dragon 2,2014,4.0,112175
25,How to Train Your Dragon: The Hidden World,166428,How to Train Your Dragon: The Hidden World,2019,4.5,196417
26,Pirates of the Caribbean: The Curse of the Bla...,22,Pirates of the Caribbean: The Curse of the Bla...,2003,4.0,6539
27,Kung Fu Panda,9502,Kung Fu Panda,2008,4.0,59784
28,Kung Fu Panda 2,49444,Kung Fu Panda 2,2011,4.0,87222
29,The Devil Wears Prada,350,The Devil Wears Prada,2006,3.0,45720
30,Serenity,452832,Serenity,2019,2.0,196895
31,Mortal Kombat,460465,Mortal Kombat,2021,3.0,240452

34

In [ ]:
unmatched = tmdb_df[~tmdb_df['tmdb_id'].isin(matched['tmdb_id'])]

matched.to_csv(data_path / 'movielens_matched.csv', index=False)
unmatched.to_csv(data_path / 'movielens_unmatched.csv', index=False)

print(f"Saved {len(matched)} matched rows to movielens_matched.csv")
print(f"Saved {len(unmatched)} unmatched rows to movielens_unmatched.csv")